// Generated from assets/about/history — Metro needs static require paths, so
// each photo is listed explicitly. Add a file to that folder and add a line here.

import type { ImageSourcePropType } from 'react-native';

export const HISTORY_IMAGES: ImageSourcePropType[] = [
  require('../../../assets/about/history/history-01.jpg'),
  require('../../../assets/about/history/history-02.jpg'),
  require('../../../assets/about/history/history-03.jpg'),
  require('../../../assets/about/history/history-04.jpg'),
  require('../../../assets/about/history/history-05.jpg'),
  require('../../../assets/about/history/history-06.jpg'),
  require('../../../assets/about/history/history-07.jpg'),
  require('../../../assets/about/history/history-08.jpg'),
  require('../../../assets/about/history/history-09.jpg'),
  require('../../../assets/about/history/history-10.jpg'),
  require('../../../assets/about/history/history-11.jpg'),
  require('../../../assets/about/history/history-12.jpg'),
  require('../../../assets/about/history/history-13.jpg'),
  require('../../../assets/about/history/history-14.jpg'),
  require('../../../assets/about/history/history-15.jpg'),
  require('../../../assets/about/history/history-16.jpg'),
  require('../../../assets/about/history/history-17.jpg'),
  require('../../../assets/about/history/history-18.jpg'),
  require('../../../assets/about/history/history-19.jpg'),
  require('../../../assets/about/history/history-20.jpg'),
  require('../../../assets/about/history/history-21.jpg'),
  require('../../../assets/about/history/history-22.jpg'),
  require('../../../assets/about/history/history-23.jpg'),
  require('../../../assets/about/history/history-24.jpg'),
  require('../../../assets/about/history/history-25.jpg'),
  require('../../../assets/about/history/history-26.jpg'),
  require('../../../assets/about/history/history-27.jpg'),
  require('../../../assets/about/history/history-28.jpg'),
  require('../../../assets/about/history/history-29.jpg'),
  require('../../../assets/about/history/history-30.jpg'),
  require('../../../assets/about/history/history-31.jpg'),
  require('../../../assets/about/history/history-32.jpg'),
  require('../../../assets/about/history/history-33.jpg'),
  require('../../../assets/about/history/history-34.jpg'),
  require('../../../assets/about/history/history-35.jpg'),
  require('../../../assets/about/history/history-36.jpg'),
  require('../../../assets/about/history/history-37.jpg'),
  require('../../../assets/about/history/history-38.jpg'),
  require('../../../assets/about/history/history-39.jpg'),
  require('../../../assets/about/history/history-40.jpg'),
  require('../../../assets/about/history/history-41.jpg'),
  require('../../../assets/about/history/history-42.jpg'),
  require('../../../assets/about/history/history-43.jpg'),
  require('../../../assets/about/history/history-44.jpg'),
  require('../../../assets/about/history/history-45.jpg'),
  require('../../../assets/about/history/history-46.jpg'),
  require('../../../assets/about/history/history-47.jpg'),
  require('../../../assets/about/history/history-48.jpg'),
  require('../../../assets/about/history/history-49.jpg'),
];
